In [1]:
import numpy
import cv2

In [2]:
image = cv2.imread('smallgray.png', 0)
image

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [3]:
# Slice from row 0 to 2. Slice from colum 2 to 4 in the sliced rows
image[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [4]:
# Show number of rows, columns
image.shape

(3, 5)

In [5]:
# Get value from y=2 and x=4
image[2, 4]

182

In [6]:
# Iterate normal array
for i in image:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [7]:
# Exchange columns to row to iterate
for i in image.T:
    print (i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [8]:
# Iterate a unidimensional array
for i in image.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [21]:
# Concatenate arrays by merging line by line (or horizontally)
image_stack = numpy.hstack((image, image, image))
image_stack

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
        121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
        255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
         97, 182]], dtype=uint8)

In [23]:
# Split array in 3 arrays horizontally
numpy.hsplit(image_stack, 3)

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [26]:
# Split array vertically 
numpy.vsplit(image_stack, 3)

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
         121, 143]], dtype=uint8),
 array([[198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
         255, 147]], dtype=uint8),
 array([[209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
          97, 182]], dtype=uint8)]

In [27]:
# Concatenate array by adding more lines (or vertically)
image_stack = numpy.vstack((image, image, image))
image_stack

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)